### ISSUE TITLE
Crypto: Bruce Schneier and Matthew Green

### ISSUE THREAD

**Issue by Strilanc** [j2kun/blogs-by-experts#3]
Bruce Schneier

'Schneier on Security'

Example post/essay: "Why Cryptography Is Harder Than It Looks" https://www.schneier.com/essays/archives/1997/01/why_cryptography_is.html

---

Matthew Green

'A Few Thoughts on Cryptographic Engineering'

Example post: "Attack of the week: OpenSSL Heartbleed" http://blog.cryptographyengineering.com/2014/04/attack-of-week-openssl-heartbleed.html

**Comment by j2kun** [comment]
Thanks!
